/**
 * A real shell putting its line editor up, chunked exactly as a pty delivered
 * it, and stopping while it was still waiting for a line.
 *
 * Generated by apps/server/src/capture-bracketed-paste-fixtures.test.ts (see
 * that file for how to re-run the capture, and for why it is a shell rather
 * than a script printing the sequence itself). Never edited by hand: what the
 * pane's paste test reads off these bytes is whether the emulator ends up in
 * bracketed paste mode, and hand-written bytes would carry their author's
 * answer to that already.
 *
 * Replaying these leaves an emulator with bracketed paste ON, which is the
 * state a paste has to be wrapped in. The shell turns it off again as soon as
 * it accepts a line, so the capture stops before that.
 *
 * Base64 rather than byte arrays so the file stays reviewable; decoded here
 * with atob, which exists in every browser and in the node vitest runs on.
 */

function decode(base64: string): Uint8Array {
  const text = atob(base64);
  const bytes = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i += 1) bytes[i] = text.charCodeAt(i);
  return bytes;
}

const encoded: readonly string[] = [
  'ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANDQ==',
  'DRtbMG0bWzI3bRtbMjRtG1tKcGFuZSQgG1tLG1s/MjAwNGg=',
];

/** Oldest first, boundaries preserved. Callers must not mutate the arrays. */
export const bracketedPasteChunks: readonly Uint8Array[] = encoded.map(decode);
