/**
 * Real terminal output, chunked exactly as a pty delivered it.
 *
 * Generated by apps/agentplexd/src/server/capture-terminal-fixtures.test.ts
 * (see that file for how to re-run the capture). Never edited by hand: the
 * chunk feed's whole-chunk trimming rule exists because escape sequences
 * cross chunk boundaries, and only a real pty produces real boundaries.
 *
 * Base64 rather than byte arrays so the file stays reviewable; decoded here
 * with atob, which exists in every browser and in the node vitest runs on.
 */

function decode(base64: string): Uint8Array {
  const text = atob(base64);
  const bytes = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i += 1) bytes[i] = text.charCodeAt(i);
  return bytes;
}

const encoded: readonly string[] = [
  'G1szODs1OzI0NW0xNDoyMDoxMRtbMG0gG1sxbSQgcG5wbSB0ZXN0IGF1dGgbWzBtDQ0K',
  'ICAbWzMybeKckxtbMG0gcmVmcmVzaCB0b2tlbiByb3RhdGVzICgyMTJtcykNDQo=',
  'ICAbWzMxbeKclRtbMG0gY29uY3VycmVudCByZWZyZXNoIGRlZHVwZXMgG1s0MTs5N20gRkFJTCAbWzBtDQ0K',
  'G1szNm3ioIsbWzBtIHRoaW5raW5nLi4u',
  'DRtbMksbWzM2beKgmRtbMG0gdGhpbmtpbmcsIGhhcmRlci4uLg==',
  'DRtbMksbWzMzbeKWuBtbMG0gcGxhbjogc2luZ2xlIGluLWZsaWdodCBwcm9taXNlDQ0K',
  'G1syQRtbMErilIzilIAgZGlmZiDilIDilJANDQrilIIgG1szMm0rMTgbWzBtIBtbMzFtLTQbWzBtIOKUgg0NCuKUlOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUmA0NCg==',
  'G1szODs1OzEwMG3ilogbWzM4OzU7MTAxbeKWiBtbMzg7NTsxMDJt4paIG1szODs1OzEwM23ilogbWzM4OzU7MTA0beKWiBtbMzg7NTsxMDVt4paIG1szODs1OzEwNm3ilogbWzM4OzU7MTA3beKWiBtbMzg7NTsxMDht4paIG1szODs1OzEwOW3ilogbWzM4OzU7MTEwbeKWiBtbMzg7NTsxMTFt4paIG1szODs1OzExMm3ilogbWzM4OzU7MTEzbeKWiBtbMzg7NTsxMTRt4paIG1szODs1OzExNW3ilogbWzM4OzU7MTE2beKWiBtbMzg7NTsxMTdt4paIG1szODs1OzExOG3ilogbWzM4OzU7MTE5beKWiBtbMzg7NTsxMjBt4paIG1szODs1OzEyMW3ilogbWzM4OzU7MTIybeKWiBtbMzg7NTsxMjNt4paIG1szODs1OzEyNG3ilogbWzM4OzU7MTI1beKWiBtbMzg7NTsxMjZt4paIG1szODs1OzEyN23ilogbWzM4OzU7MTI4beKWiBtbMzg7NTsxMjlt4paIG1szODs1OzEzMG3ilogbWzM4OzU7MTMxbeKWiBtbMzg7NTsxMzJt4paIG1szODs1OzEzM23ilogbWzM4OzU7MTM0beKWiBtbMzg7NTsxMzVt4paIG1szODs1OzEzNm3ilogbWzM4OzU7MTM3beKWiBtbMzg7NTsxMzht4paIG1szODs1OzEzOW3ilogbWzBtDQ0K',
];

/** Oldest first, boundaries preserved. Callers must not mutate the arrays. */
export const ptyChunks: readonly Uint8Array[] = encoded.map(decode);
