/**
 * The task prompt, cut into the runs that are drawn as prose and the ones that
 * are drawn as a branch.
 *
 * The mockup marks a branch name inside the sentence in monospace ("...open a
 * PR against `main`"), which is worth having: a branch is a token in the middle
 * of ordinary English and the eye needs help finding where it starts and stops.
 * What makes it delicate is where the sentence comes from. The task is a
 * person's own prompt, typed into the start form, and it is not markup -- there
 * is no syntax in it to read, only words, so every mark this file draws is a
 * guess about a word.
 *
 * So the rule is conservative in one direction on purpose. A branch that goes
 * unmarked reads as what it is, a word in a sentence; a word wrongly marked
 * puts a monospace box around a noun and makes the prose look like it was
 * generated by something that did not understand it. `main` really is a branch
 * in "open a PR against main" and really is not one in "keep the main loop
 * responsive", and nothing in the string says which -- so the marker only
 * claims the cases where the shape of the token or the word in front of it
 * leaves no other reading. Everything else stays prose.
 *
 * And it never rewrites. The segments concatenate back to exactly the prompt
 * that was passed in, punctuation, whitespace and all: a marker that stripped
 * the backticks somebody typed, or that trimmed a token to make it match,
 * would be showing the user a sentence they did not write.
 */

/**
 * A run of the prompt and whether it is drawn as a branch.
 *
 * Not offsets into the original: the block renders these in order and the only
 * thing it can do with an offset is slice the string again. The text is
 * carried so the one rule that matters -- concatenating the segments gives the
 * prompt back -- is checkable by reading them.
 */
export interface TaskSegment {
  readonly text: string;
  readonly branch: boolean;
}

/**
 * The names a repository's trunk actually goes by.
 *
 * Deliberately short. These are the words that are worth recognising because
 * they are the ones a prompt names without any other context ("open a PR
 * against main"); a longer list of plausible branch words would only widen the
 * set of English nouns this file is willing to mark.
 */
const DEFAULT_BRANCHES: ReadonlySet<string> = new Set(['main', 'master', 'develop', 'trunk']);

/**
 * The words after which a default branch name can only be a branch.
 *
 * This is the whole of the context the marker reads, and it is one word wide
 * on purpose. "Against", "onto" and "into" are followed by a branch or by
 * nothing that reads like this; "to" and "on" are followed by anything at all,
 * so they are not here and "push to main" goes unmarked. That is the trade
 * this file is making: a missed mark, not a marked noun.
 */
const BRANCH_LEAD_INS: ReadonlySet<string> = new Set([
  'against',
  'onto',
  'into',
  'from',
  'off',
  'atop',
  'branch',
  'targeting',
  'rebase',
  'rebased',
  'merge',
  'merged',
]);

/**
 * The prefixes a branch with a slash in it is actually named with.
 *
 * A slash alone proves nothing -- `src/auth/refresh.ts` has two -- so the
 * first segment has to be one of the conventional kinds of branch. Anything
 * else with a slash in it (`robert/spike`, `origin/main`, a bare directory
 * name) is left as prose, because on half the repositories in the world it is
 * a branch and on the other half it is a folder.
 */
const BRANCH_PREFIXES: ReadonlySet<string> = new Set([
  'fix',
  'feat',
  'feature',
  'bugfix',
  'hotfix',
  'chore',
  'release',
  'refactor',
  'docs',
  'spike',
  'test',
  'wip',
]);

/** The shape of a prefixed branch: kind, slash, and a name made of name-ish characters. */
const PREFIXED_BRANCH = /^([a-z]+)\/([A-Za-z0-9._/-]+)$/;

/** A trailing `.ts`, `.md`, `.json`: whatever it starts with, it is a file. */
const FILE_EXTENSION = /\.[A-Za-z0-9]{1,5}$/;

/** Punctuation a token can be wrapped in without stopping being that token. */
const LEADING_PUNCTUATION = /^[`"'([{]+/;
const TRAILING_PUNCTUATION = /[`"')\]}.,;:!?]+$/;

/**
 * The token itself, with whatever the sentence wrapped it in taken off.
 *
 * The wrapping is measured and not discarded: the caller draws it, unmarked,
 * on either side of the mark. A backtick somebody typed stays on the screen.
 */
interface Token {
  readonly before: string;
  readonly core: string;
  readonly after: string;
}

function splitToken(token: string): Token {
  const before = LEADING_PUNCTUATION.exec(token)?.[0] ?? '';
  const rest = token.slice(before.length);
  const after = TRAILING_PUNCTUATION.exec(rest)?.[0] ?? '';
  return { before, core: rest.slice(0, rest.length - after.length), after };
}

/**
 * Whether this token, after that one, can only be a branch.
 *
 * `previous` is the last core token before it, lowercased, or the empty string
 * at the start of the prompt -- a prompt that opens with `main` has nothing in
 * front of it to disambiguate the word, so it stays prose.
 */
function isBranch(core: string, previous: string): boolean {
  if (core.length === 0) return false;
  if (DEFAULT_BRANCHES.has(core.toLowerCase())) return BRANCH_LEAD_INS.has(previous);
  const prefixed = PREFIXED_BRANCH.exec(core);
  if (prefixed === null) return false;
  const [, kind, name] = prefixed;
  if (kind === undefined || name === undefined) return false;
  if (!BRANCH_PREFIXES.has(kind)) return false;
  // `docs/architecture.md` starts like a branch and is a file.
  return !FILE_EXTENSION.test(name);
}

/**
 * The prompt, as the runs to draw.
 *
 * Unmarked runs are merged, so a prompt with no branch in it is one segment
 * and renders as one piece of prose rather than as a word-by-word rebuild of
 * the sentence.
 */
export function markTaskProse(task: string): readonly TaskSegment[] {
  const segments: TaskSegment[] = [];
  let prose = '';
  let previous = '';

  function flushProse(): void {
    if (prose.length === 0) return;
    segments.push({ text: prose, branch: false });
    prose = '';
  }

  // The capture group keeps the whitespace in the list, which is how the
  // segments can add back up to the prompt.
  for (const piece of task.split(/(\s+)/)) {
    if (piece.length === 0) continue;
    if (/^\s+$/.test(piece)) {
      prose += piece;
      continue;
    }
    const { before, core, after } = splitToken(piece);
    if (isBranch(core, previous)) {
      prose += before;
      flushProse();
      segments.push({ text: core, branch: true });
      prose = after;
    } else {
      prose += piece;
    }
    previous = core.toLowerCase();
  }

  flushProse();
  return segments;
}
