/**
 * A real program drawing a bordered panel of wide characters, chunked exactly
 * as a pty delivered it.
 *
 * Generated by apps/server/src/terminal/capture-unicode-width-fixtures.test.ts (see
 * that file for how to re-run the capture, and for why it is a shell rather
 * than a coding agent doing the drawing). Never edited by hand: what the
 * pane's Unicode test reads off these bytes is which column each glyph ends
 * in, and hand-written bytes would carry their author's answer to that
 * question already.
 *
 * The panel is padded by the program that drew it for a two-column emoji, so
 * its right border is in one column on every row only if the emulator
 * measures that emoji the way the program did. These bytes contain an emoji,
 * which nothing else in this repository does: it is the thing under test.
 *
 * Base64 rather than byte arrays so the file stays reviewable; decoded here
 * with atob, which exists in every browser and in the node vitest runs on.
 */

function decode(base64: string): Uint8Array {
  const text = atob(base64);
  const bytes = new Uint8Array(text.length);
  for (let i = 0; i < text.length; i += 1) bytes[i] = text.charCodeAt(i);
  return bytes;
}

const encoded: readonly string[] = [
  'G1szODs1OzI0NW3ilIzilIAg5pel5pys6KqeIOKUgOKUkBtbMG0NCg==',
  'G1szODs1OzI0NW3ilIIbWzBtIPCfp5Egb2sgICAgG1szODs1OzI0NW3ilIIbWzBtDQo=',
  'G1szODs1OzI0NW3ilJTilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilJgbWzBtDQo=',
  '8J+nkeKAjfCfkrsbWzM4OzU7MjQ1beKUghtbMG0NCg==',
];

/** Oldest first, boundaries preserved. Callers must not mutate the arrays. */
export const unicodeChunks: readonly Uint8Array[] = encoded.map(decode);
