import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { nodeProjectFiles } from './node-project-files.js';
import { PROJECT_FILE_NAME } from './project-files.js';

/**
 * Captures what a real `readdir` and `stat` say about a project folder, for
 * the document listing's tests.
 *
 * The listing rule is a filter over a folder that holds more than documents:
 * the note `ensureProjectFiles` writes, the hidden temporary file a write
 * goes through, whatever a person left there by hand. A test of that rule
 * against entries typed into the test would prove the filter handles what
 * its author imagined a folder contains. So this makes a folder with each of
 * those things in it, lists it through the real seam, and records the answer
 * verbatim -- the names as the disk returned them, the sizes and times as it
 * recorded them.
 *
 * A test file so it runs under vitest; gated on an environment variable so an
 * ordinary run never rewrites the fixture. To re-capture, from apps/server:
 *
 *   CAPTURE_FIXTURES=1 pnpm vitest run src/capture-doc-listing-fixture.test.ts
 */

/**
 * What the folder holds. The documents first, then everything a folder
 * accumulates that is not one: the note, a temporary file from an
 * interrupted write, a file with no extension, an extension in the wrong
 * case, a hidden file, and a subdirectory.
 */
const FOLDER: Readonly<Record<string, string>> = {
  'plan.md': '# Plan\n\n- read the failing test\n',
  'notes.txt': 'a note\n',
  'results.csv': 'case,ms\nrefresh,212\n',
  'settings.json': '{ "theme": "dark" }\n',
  [PROJECT_FILE_NAME]:
    '{ "projectKey": "agentplex-0123456789abcdef", "workingTree": "/srv/work" }\n',
  '.plan.md.2f1c9a6e-3b7d-4c8e-9f0a-1b2c3d4e5f60.tmp': '# Plan\n\n- half of a',
  README: 'no extension\n',
  'draft.MD': 'wrong case\n',
  '.hidden.md': 'hidden\n',
};

describe.runIf(process.env.CAPTURE_FIXTURES === '1')('capturing the doc listing fixture', () => {
  it('lists a real folder and writes what the disk said', async () => {
    const scratch = await mkdtemp(join(tmpdir(), 'agentplex-doc-listing-'));
    try {
      for (const [name, contents] of Object.entries(FOLDER)) {
        await writeFile(join(scratch, name), contents, 'utf8');
      }
      await mkdir(join(scratch, 'attachments'));

      const listing = await nodeProjectFiles.listFiles(scratch);
      expect(listing.kind).toBe('listed');
      if (listing.kind !== 'listed') return;

      // Sorted by name so a re-capture on a disk that lists in another order
      // leaves a clean tree; the order a directory is read in is not a fact
      // the fixture is about.
      const entries = [...listing.entries].sort((a, b) => a.name.localeCompare(b.name));
      // Single quotes, and one field per line, which prettier keeps as it
      // finds it, so a re-capture leaves a clean tree.
      const lines = entries
        .map((entry) =>
          [
            '    {',
            `      name: '${entry.name}',`,
            `      updatedAt: ${String(entry.updatedAt)},`,
            `      bytes: ${String(entry.bytes)},`,
            '    },',
          ].join('\n'),
        )
        .join('\n');
      const module = `import type { FileListing } from './project-files.js';

/**
 * What a real \`readdir\` and \`stat\` said about a project folder holding
 * four documents and five things that are not documents.
 *
 * Generated by apps/server/src/capture-doc-listing-fixture.test.ts (see that
 * file for what was in the folder and how to re-run the capture). Never
 * edited by hand: the listing rule is a filter over what a disk actually
 * returns, and only a disk produces that.
 */
export const capturedListing: FileListing = {
  kind: 'listed',
  entries: [
${lines}
  ],
};
`;

      const target = new URL('./doc-listing.fixture.ts', import.meta.url);
      await writeFile(target, module, 'utf8');
      process.stdout.write(`wrote ${String(entries.length)} entries to ${fileURLToPath(target)}\n`);
    } finally {
      await rm(scratch, { recursive: true, force: true });
    }
  });
});
