import { writeFile } from 'node:fs/promises';
import { cpus, loadavg, platform, release } from 'node:os';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * Captures what `os.cpus()` and `os.loadavg()` actually return, twice, with
 * real work done in between.
 *
 * The reader's whole job is to difference two counter readings, and a
 * hand-written pair of tick counts would test somebody's idea of what a kernel
 * counts rather than what one counts. One fixture per platform, because which
 * of the five counters a kernel moves at all, how coarsely it moves them, and
 * what magnitudes they reach are properties of that kernel and are invisible
 * until captured -- a share computed from one platform's numbers is no evidence
 * about the other's. Both are here so that a change to the arithmetic has to
 * survive real counters from both the machines this server runs on.
 *
 * The delay between the two readings is spent burning cpu on purpose. Two
 * readings taken back to back on an idle machine differ by almost nothing, and
 * a fixture whose busy share is a rounding error exercises none of the
 * arithmetic.
 *
 * A test file so it runs under vitest (the one runner here that resolves `.js`
 * specifiers to `.ts` sources); gated on an environment variable so an ordinary
 * run never rewrites the fixture. To re-capture, from apps/server:
 *
 *   CAPTURE_FIXTURES=1 pnpm vitest run src/capture-machine-load-fixtures.test.ts
 *
 * and again inside the container for the Linux one:
 *
 *   pnpm docker:test -- --filter @agentplex/server
 */

/** Long enough that the kernel's accounting has ticked well past its own resolution. */
const BURN_MS = 1_500;

function burn(ms: number): void {
  const until = Date.now() + ms;
  // Deliberately hot, and deliberately not something the engine can elide: the
  // point of the fixture is a window in which this machine was busy.
  let sink = 0;
  while (Date.now() < until) sink = (sink + Math.sqrt(sink + 1)) % 1e9;
  expect(sink).toBeGreaterThanOrEqual(0);
}

describe.runIf(process.env.CAPTURE_FIXTURES === '1')('capturing machine load fixtures', () => {
  it('reads the real counters twice with real work in between', async () => {
    const before = { at: Date.now(), cpus: cpus().map(({ times }) => times) };
    burn(BURN_MS);
    const after = { at: Date.now(), cpus: cpus().map(({ times }) => times) };

    // A capture on a machine with no cpu accounting would be a fixture of the
    // degenerate case, and the degenerate case is tested from an empty list.
    expect(before.cpus.length).toBeGreaterThan(0);
    expect(after.cpus.length).toBe(before.cpus.length);

    const lines = (times: readonly { readonly [key: string]: number }[]): string =>
      times
        .map(
          (time) =>
            `  { user: ${String(time.user)}, nice: ${String(time.nice)}, sys: ${String(time.sys)}, idle: ${String(time.idle)}, irq: ${String(time.irq)} },`,
        )
        .join('\n');

    const average = loadavg();
    const module = `/**
 * Real \`os.cpus()\` counters and \`os.loadavg()\`, captured on ${platform()} ${release()}.
 *
 * Generated by apps/server/src/capture-machine-load-fixtures.test.ts (see that
 * file for how to re-run the capture). Never edited by hand: the point of it is
 * that the tick counts are a kernel's and not an author's.
 *
 * The two readings are ${String(after.at - before.at)}ms apart, with that interval spent burning cpu.
 */

import type { CpuTimes } from './machine-load.js';

/** Wall milliseconds between the two readings, as this machine's clock measured it. */
export const windowMs = ${String(after.at - before.at)};

export const before: readonly CpuTimes[] = [
${lines(before.cpus)}
];

export const after: readonly CpuTimes[] = [
${lines(after.cpus)}
];

/** What \`os.loadavg()\` answered on this platform, straight through. */
export const loadAverage: [number, number, number] = [${average.map((one) => String(one)).join(', ')}];
`;

    const target = new URL(`./machine-load-${platform()}.fixture.ts`, import.meta.url);
    await writeFile(target, module, 'utf8');
    process.stdout.write(`wrote ${String(before.cpus.length)} cpus to ${fileURLToPath(target)}\n`);
  });
});
