import type { FileListing } from './project-files.js';

/**
 * What a real `readdir` and `stat` said about a project folder holding
 * four documents and five things that are not documents.
 *
 * Generated by apps/server/src/capture-doc-listing-fixture.test.ts (see that
 * file for what was in the folder and how to re-run the capture). Never
 * edited by hand: the listing rule is a filter over what a disk actually
 * returns, and only a disk produces that.
 */
export const capturedListing: FileListing = {
  kind: 'listed',
  entries: [
    {
      name: '.hidden.md',
      updatedAt: 1789249561628,
      bytes: 7,
    },
    {
      name: '.plan.md.2f1c9a6e-3b7d-4c8e-9f0a-1b2c3d4e5f60.tmp',
      updatedAt: 1789249561628,
      bytes: 19,
    },
    {
      name: 'draft.MD',
      updatedAt: 1789249561628,
      bytes: 11,
    },
    {
      name: 'notes.txt',
      updatedAt: 1789249561627,
      bytes: 7,
    },
    {
      name: 'plan.md',
      updatedAt: 1789249561627,
      bytes: 32,
    },
    {
      name: 'project.json',
      updatedAt: 1789249561628,
      bytes: 75,
    },
    {
      name: 'README',
      updatedAt: 1789249561628,
      bytes: 13,
    },
    {
      name: 'results.csv',
      updatedAt: 1789249561627,
      bytes: 20,
    },
    {
      name: 'settings.json',
      updatedAt: 1789249561627,
      bytes: 20,
    },
  ],
};
