/**
 * Real `os.cpus()` counters and `os.loadavg()`, captured on linux 6.10.14-linuxkit.
 *
 * Generated by apps/server/src/capture-machine-load-fixtures.test.ts (see that
 * file for how to re-run the capture). Never edited by hand: the point of it is
 * that the tick counts are a kernel's and not an author's.
 *
 * The two readings are 1500ms apart, with that interval spent burning cpu.
 */

import type { CpuTimes } from './machine-load.js';

/** Wall milliseconds between the two readings, as this machine's clock measured it. */
export const windowMs = 1500;

export const before: readonly CpuTimes[] = [
  { user: 1720, nice: 0, sys: 600, idle: 215680, irq: 0 },
  { user: 2040, nice: 0, sys: 450, idle: 215800, irq: 0 },
  { user: 2160, nice: 0, sys: 430, idle: 216820, irq: 0 },
  { user: 2920, nice: 0, sys: 460, idle: 215910, irq: 0 },
  { user: 1740, nice: 0, sys: 360, idle: 217280, irq: 0 },
  { user: 1910, nice: 0, sys: 370, idle: 217140, irq: 0 },
  { user: 3440, nice: 0, sys: 610, idle: 215280, irq: 0 },
  { user: 1360, nice: 0, sys: 310, idle: 217730, irq: 0 },
  { user: 1980, nice: 0, sys: 400, idle: 217030, irq: 0 },
  { user: 1440, nice: 0, sys: 370, idle: 217250, irq: 0 },
  { user: 2970, nice: 0, sys: 370, idle: 216080, irq: 0 },
  { user: 3100, nice: 0, sys: 460, idle: 215860, irq: 0 },
  { user: 2610, nice: 0, sys: 430, idle: 216340, irq: 0 },
  { user: 1650, nice: 0, sys: 330, idle: 217480, irq: 0 },
];

export const after: readonly CpuTimes[] = [
  { user: 1720, nice: 0, sys: 600, idle: 217180, irq: 0 },
  { user: 3540, nice: 0, sys: 450, idle: 215800, irq: 0 },
  { user: 2160, nice: 0, sys: 430, idle: 218310, irq: 0 },
  { user: 2920, nice: 0, sys: 460, idle: 217410, irq: 0 },
  { user: 1740, nice: 0, sys: 360, idle: 218780, irq: 0 },
  { user: 1910, nice: 0, sys: 370, idle: 218640, irq: 0 },
  { user: 3440, nice: 0, sys: 610, idle: 216780, irq: 0 },
  { user: 1360, nice: 0, sys: 310, idle: 219230, irq: 0 },
  { user: 1980, nice: 0, sys: 400, idle: 218530, irq: 0 },
  { user: 1440, nice: 0, sys: 370, idle: 218750, irq: 0 },
  { user: 2970, nice: 0, sys: 370, idle: 217570, irq: 0 },
  { user: 3100, nice: 0, sys: 460, idle: 217360, irq: 0 },
  { user: 2610, nice: 0, sys: 430, idle: 217840, irq: 0 },
  { user: 1650, nice: 0, sys: 330, idle: 218980, irq: 0 },
];

/** What `os.loadavg()` answered on this platform, straight through. */
export const loadAverage: [number, number, number] = [0.3, 0.08, 0.02];
