/**
 * Real `os.cpus()` counters and `os.loadavg()`, captured on darwin 25.6.0.
 *
 * Generated by apps/server/src/capture-machine-load-fixtures.test.ts (see that
 * file for how to re-run the capture). Never edited by hand: the point of it is
 * that the tick counts are a kernel's and not an author's.
 *
 * The two readings are 1500ms apart, with that interval spent burning cpu.
 */

import type { CpuTimes } from './machine-load.js';

/** Wall milliseconds between the two readings, as this machine's clock measured it. */
export const windowMs = 1500;

export const before: readonly CpuTimes[] = [
  { user: 6820010, nice: 0, sys: 3430450, idle: 37535800, irq: 0 },
  { user: 6331540, nice: 0, sys: 2899090, idle: 38624710, irq: 0 },
  { user: 5525060, nice: 0, sys: 2188360, idle: 40227020, irq: 0 },
  { user: 4963680, nice: 0, sys: 1771320, idle: 41259270, irq: 0 },
  { user: 1824010, nice: 0, sys: 330810, idle: 45873890, irq: 0 },
  { user: 1744010, nice: 0, sys: 318430, idle: 45969230, irq: 0 },
  { user: 1685420, nice: 0, sys: 310370, idle: 46036870, irq: 0 },
  { user: 1639180, nice: 0, sys: 304960, idle: 46089410, irq: 0 },
  { user: 1509410, nice: 0, sys: 290910, idle: 46232640, irq: 0 },
  { user: 2959480, nice: 0, sys: 795730, idle: 44233300, irq: 0 },
  { user: 2707520, nice: 0, sys: 654780, idle: 44631780, irq: 0 },
  { user: 2488970, nice: 0, sys: 523980, idle: 44991300, irq: 0 },
  { user: 2354820, nice: 0, sys: 466210, idle: 45190760, irq: 0 },
  { user: 2207970, nice: 0, sys: 429550, idle: 45377740, irq: 0 },
];

export const after: readonly CpuTimes[] = [
  { user: 6820030, nice: 0, sys: 3430480, idle: 37537240, irq: 0 },
  { user: 6331550, nice: 0, sys: 2899110, idle: 38626170, irq: 0 },
  { user: 5525060, nice: 0, sys: 2188550, idle: 40228330, irq: 0 },
  { user: 4963680, nice: 0, sys: 1771320, idle: 41260760, irq: 0 },
  { user: 1824010, nice: 0, sys: 330810, idle: 45875390, irq: 0 },
  { user: 1744010, nice: 0, sys: 318430, idle: 45970730, irq: 0 },
  { user: 1685420, nice: 0, sys: 310370, idle: 46038370, irq: 0 },
  { user: 1639180, nice: 0, sys: 304960, idle: 46090910, irq: 0 },
  { user: 1509410, nice: 0, sys: 290910, idle: 46234140, irq: 0 },
  { user: 2959510, nice: 0, sys: 795770, idle: 44234730, irq: 0 },
  { user: 2708870, nice: 0, sys: 654790, idle: 44631920, irq: 0 },
  { user: 2489100, nice: 0, sys: 523990, idle: 44992660, irq: 0 },
  { user: 2354850, nice: 0, sys: 466220, idle: 45192230, irq: 0 },
  { user: 2207980, nice: 0, sys: 429550, idle: 45379240, irq: 0 },
];

/** What `os.loadavg()` answered on this platform, straight through. */
export const loadAverage: [number, number, number] = [1.49951171875, 3.03271484375, 3.66796875];
